### PR TITLE
testing/4.0.1: Update version to 4.0.1 and update SHA256 for targz

### PR DESCRIPTION
**Pull request by jmarrec**
cf https://github.com/bincrafters/community/issues/978

Tested locally on Ubuntu 18.04, works fine.

### CODE REVIEW

**Comment by madebr** [comment]
Looks fine!

@Croydon Should this (and cccl_installer) be moved to conan-center-index?
Does conan-center-index support mingw?

**Comment by Croydon** [comment]
Conan Center Index does not offer MinGW builds. If bugs with recipes and MinGW are getting reported we try to fix them.

In the mid and long term all stable recipes from Bincrafters will get migrated over to CCI. Bincrafters will serve as a testing place, where we can collaboratively get recipes mature. Some recipes like Qt or module Boost take a long time to get to such a point.

swig/cccl is nothing I would **personally** prioritize for getting into CCI right now.

As long as the repositories aren't archived we still happily receive pull requests and contributions. Thanks @jmarrec!

I have merged this pull request into a new 4.0.1 branch: https://ci.appveyor.com/project/bincrafters/conan-swig-installer/builds/27671897

32-bit fails. Could you please explain this custom code in the build.py file @madebr? I'm not sure what it is supposed to do or why we need it https://github.com/bincrafters/conan-swig_installer/blame/testing/4.0.0/build.py#L12 🤔 

If this is some special workaround for MinGW, then let's just build it with Visual Studio which should work now thanks to CCCL, right?

**Comment by madebr** [comment]
@Croydon : `conan-package-tools` will only add `mingw_installer` to the build_requires and add the appropriate compiler settings when using `add_common_builds`.
When using `add` on a builder, it will use the default compiler (which on Windows is Visual Studio)
In other worlds, I saw no other way to reach this line:
https://github.com/conan-io/conan-package-tools/blob/3cd84876dd8191fd675a397a954786199f0f3502/cpt/builds_generator.py#L146

I looked in my private appveyor history, and these lines try to fix this error:
https://ci.appveyor.com/project/madebr/conan-swig-installer/builds/24515420/job/i9xuncwf5bc5vp5q
You'll see that conan tries to use Visual Studio, even though the ci has the MINGW_CONFIGURATIONS variable set.

So what I did was add all builds using `add_common_builds`,
copy the compiler settings and build_requires, remove all the builds added by `add_common_builds` and add a new build.

The appveyor CI error is weird, it appears that `add_common_builds` added no builds.

**Comment by Croydon** [comment]
Merged via https://github.com/bincrafters/conan-swig_installer/commit/5a1494c8b7c119cbc08a4af98b012787b2e0615c

Replaced MinGW with Visual Studio via https://github.com/bincrafters/conan-swig_installer/commit/d5672a0a30b25d8a533db3a03063c94aeca30ec0

Thanks!

**Pull request closed without merging**
